 version: 2
 jobs:
   build:
     docker:
       - image: circleci/node:12.0.0
     steps:
      - checkout
      # - run: 
      #   name: update-npm
      #   command: 'npm install -g npm@latest'
      # # -restore_cache:
      #   key: dependency-cache-({ checksum "package-lock.json"})
      # -run:
      #   name: install-npm-wee
      #   command: npm install
      # -save_cache:
      #   key: dependency-cache-{{chechsum "package-lock.json"}}
      #   paths:
      #     - ./node_modules
      # -run:
      #   name: test
      #   command: npm run test
      # -run:
      #   name: code-coverage
      #   command: './node_modules/.bin/nyc report --resporter=text-lcov'