# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      # hunguphere
      - run:
        name: The First Step
        command: 'npm install npm@latest'
      - restore_cache: 
        key: dependency-cache-{{ checksum "package-lock.json" }}
      - save_cache:
        key: dependency-cache-{{ cheksum "package-lock.json" }}
        paths:
           - node_modules