# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  build:
    docker:
      -image: circleci/node:10-browsers
    steps:
      -checkout
      # hunguphere
      -run:
        name: The First Step
        command: |
          echo 'Hello World!'
          echo 'This is my delivery pipeline'
      -run:
        name: Code AHas Arrived
        command: |
          ls -al
          echo '^^^^should look familiar^^^'